receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
    use_internal_logger: false

service:
  telemetry:
    logs:
      level: "info"
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
